import { fromGrid, type Sprite } from "@mockintosh/sdk";
import type { ToolId } from "./tools";

/** A selected object, as in Figma or Sketch: a circle and a square inside a dotted selection with corner handles, on a white tile with the App Store icon's corners. `#` ink, `o` paper, `.` clear. */
export const APP_ICON: Sprite = fromGrid(32, 32, [
  ".....######################.....",
  "...##oooooooooooooooooooooo##...",
  "..#oooooooooooooooooooooooooo#..",
  ".#oooooooooooooooooooooooooooo#.",
  ".#oo#####oooooooooooooo#####oo#.",
  "#ooo#ooo#oooooooooooooo#ooo#ooo#",
  "#ooo#ooo#o#o#o#o#o#o#o##ooo#ooo#",
  "#ooo#ooo#oooooooooooooo#ooo#ooo#",
  "#ooo#####oo####oooooooo#####ooo#",
  "#oooooooo##oooo##oooooooooooooo#",
  "#ooooo#o#oooooooo#ooooooo#ooooo#",
  "#ooooooo#oooooooo#ooooooooooooo#",
  "#ooooo##oooooooooo#oooooo#ooooo#",
  "#oooooo#ooooo##########oooooooo#",
  "#ooooo##ooooo#oooooooo#oo#ooooo#",
  "#oooooo#ooooo#oooooooo#oooooooo#",
  "#ooooo#o#oooo#oooooooo#oo#ooooo#",
  "#ooooooo#oooo#oooooooo#oooooooo#",
  "#ooooo#oo##oo#oooooooo#oo#ooooo#",
  "#oooooooooo###oooooooo#oooooooo#",
  "#ooooo#oooooo#oooooooo#oo#ooooo#",
  "#oooooooooooo#oooooooo#oooooooo#",
  "#ooooo#oooooo##########oo#ooooo#",
  "#ooo#####oooooooooooooo#####ooo#",
  "#ooo#ooo#oooooooooooooo#ooo#ooo#",
  "#ooo#ooo#o#o#o#o#o#o#o##ooo#ooo#",
  "#ooo#ooo#oooooooooooooo#ooo#ooo#",
  ".#oo#####oooooooooooooo#####oo#.",
  ".#oooooooooooooooooooooooooooo#.",
  "..#oooooooooooooooooooooooooo#..",
  "...##oooooooooooooooooooooo##...",
  ".....######################.....",
]);

const SELECT: Sprite = fromGrid(16, 16, [
  "                ",
  "  #             ",
  "  ##            ",
  "  # #           ",
  "  #  #          ",
  "  #   #         ",
  "  #    #        ",
  "  #     #       ",
  "  #  ####       ",
  "  #  #          ",
  "  # #           ",
  "  ## #          ",
  "  #   #         ",
  "       #        ",
  "                ",
  "                ",
]);

const TEXT: Sprite = fromGrid(16, 16, [
  "                ",
  "  ############  ",
  "  #          #  ",
  "  #          #  ",
  "      ####      ",
  "       ##       ",
  "       ##       ",
  "       ##       ",
  "       ##       ",
  "       ##       ",
  "       ##       ",
  "       ##       ",
  "     ######     ",
  "                ",
  "                ",
  "                ",
]);

const RECT: Sprite = fromGrid(16, 16, [
  "                ",
  "  ############  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  ############  ",
  "                ",
  "                ",
  "                ",
]);

const RRECT: Sprite = fromGrid(16, 16, [
  "                ",
  "    ########    ",
  "   #        #   ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "  #          #  ",
  "   #        #   ",
  "    ########    ",
  "                ",
  "                ",
  "                ",
]);

const OVAL: Sprite = fromGrid(16, 16, [
  "                ",
  "     ######     ",
  "   ##      ##   ",
  "  #          #  ",
  "  #          #  ",
  " #            # ",
  " #            # ",
  " #            # ",
  " #            # ",
  "  #          #  ",
  "  #          #  ",
  "   ##      ##   ",
  "     ######     ",
  "                ",
  "                ",
  "                ",
]);

const LINE: Sprite = fromGrid(16, 16, [
  "                ",
  "              # ",
  "             #  ",
  "            #   ",
  "           #    ",
  "          #     ",
  "         #      ",
  "        #       ",
  "       #        ",
  "      #         ",
  "     #          ",
  "    #           ",
  "   #            ",
  "  #             ",
  "                ",
  "                ",
]);

export const TOOL_ICONS: Record<ToolId, Sprite> = {
  select: SELECT,
  text: TEXT,
  rect: RECT,
  roundrect: RRECT,
  oval: OVAL,
  line: LINE,
};

/** The selected object for the application menu: the card, its corner handles, the circle and the square. */
export const APP_ICON_16: Sprite = fromGrid(16, 16, [
  "###..........###",
  "#o############o#",
  "###oooooooooo###",
  ".#ooo###oooooo#.",
  ".#oo#ooo#ooooo#.",
  ".#o#ooooo#oooo#.",
  ".#o#ooooo#oooo#.",
  ".#o#ooo######o#.",
  ".#oo#oo#oooo#o#.",
  ".#ooo###oooo#o#.",
  ".#ooooo#oooo#o#.",
  ".#ooooo#oooo#o#.",
  ".#ooooo######o#.",
  "###oooooooooo###",
  "#o############o#",
  "###..........###",
]);

/** A Canvas document: the document page with the selection, its handles, and the circle and square. */
const DOCUMENT_ICON: Sprite = fromGrid(32, 32, [
  "...###################..........",
  "...#ooooooooooooooooo##.........",
  "...#ooooooooooooooooo#o#........",
  "...#ooooooooooooooooo#oo#.......",
  "...#ooooooooooooooooo#ooo#......",
  "...#ooooooooooooooooo#oooo#.....",
  "...#ooooooooooooooooo#######....",
  "...#ooooooooooooooooooooooo#....",
  "...#ooooooooooooooooooooooo#....",
  "...#ooooooooooooooooooooooo#....",
  "...#oo###ooooooooooooo###oo#....",
  "...#oo#o##o#o#o#o#o#o##o#oo#....",
  "...#oo###oo####ooooooo###oo#....",
  "...#ooo#o##oooo##oooooo#ooo#....",
  "...#ooooo#oooooo#oooooooooo#....",
  "...#ooo##oooooooo#ooooo#ooo#....",
  "...#oooo#oooooooo#ooooooooo#....",
  "...#ooo##oooo########oo#ooo#....",
  "...#oooo#oooo#oooooo#oooooo#....",
  "...#ooo#o#ooo#oooooo#oo#ooo#....",
  "...#ooooo##oo#oooooo#oooooo#....",
  "...#ooo#ooo###oooooo#oo#ooo#....",
  "...#ooooooooo#oooooo#oooooo#....",
  "...#ooo#ooooo#oooooo#oo#ooo#....",
  "...#ooooooooo########oooooo#....",
  "...#ooo#ooooooooooooooo#ooo#....",
  "...#oo###ooooooooooooo###oo#....",
  "...#oo#o##o#o#o#o#o#o##o#oo#....",
  "...#oo###ooooooooooooo###oo#....",
  "...#ooooooooooooooooooooooo#....",
  "...#ooooooooooooooooooooooo#....",
  "...#########################....",
]);

/** The Canvas document for 16×16 views: the page with the circle and square. */
const DOCUMENT_ICON_16: Sprite = fromGrid(16, 16, [
  "..########......",
  "..#oooooo##.....",
  "..#oooooo#o#....",
  "..#oooooo#oo#...",
  "..#oooooo#####..",
  "..#oooooooooo#..",
  "..#oo##oooooo#..",
  "..#o#oo#ooooo#..",
  "..#o#o#####oo#..",
  "..#oo##ooo#oo#..",
  "..#ooo#ooo#oo#..",
  "..#ooo#ooo#oo#..",
  "..#ooo#####oo#..",
  "..#oooooooooo#..",
  "..#oooooooooo#..",
  "..############..",
]);

export const sprites: Record<string, Sprite> = {
  "canvas/icon": APP_ICON,
  "canvas/icon-16x16": APP_ICON_16,
  "canvas/document": DOCUMENT_ICON,
  "canvas/document-16x16": DOCUMENT_ICON_16,
};
