/**
 * Packs Natural Earth's 1:50m land polygons and land borders (public domain,
 * https://www.naturalearthdata.com) into `apps/earth/geography.generated.ts`
 * for the Earth app.
 *
 *   curl -LO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson
 *   curl -LO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_boundary_lines_land.geojson
 *   npx tsx scripts/build-earth-geography.ts ne_50m_land.geojson ne_50m_admin_0_boundary_lines_land.geojson
 *
 * The format is described in `apps/earth/packing.ts`.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { QUANTUM, encode, zigzag } from "../apps/earth/packing";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_PATH = path.join(ROOT, "apps", "earth", "geography.generated.ts");

type Position = [number, number];
interface Geometry {
  type: string;
  coordinates: unknown;
}

function linesOf(geometry: Geometry): Position[][] {
  switch (geometry.type) {
    case "LineString":
      return [geometry.coordinates as Position[]];
    case "MultiLineString":
    case "Polygon":
      return geometry.coordinates as Position[][];
    case "MultiPolygon":
      return (geometry.coordinates as Position[][][]).flat(1);
    default:
      throw new Error(`Unexpected geometry ${geometry.type}`);
  }
}

function read(file: string): Position[][] {
  const json = JSON.parse(fs.readFileSync(file, "utf8")) as { features: { geometry: Geometry }[] };
  return json.features.flatMap((feature) => linesOf(feature.geometry));
}

function pack(lines: Position[][], closed: boolean): string {
  const values: number[] = [];
  let count = 0;
  let px = 0;
  let py = 0;
  for (const line of lines) {
    const points: Position[] = [];
    for (const [lon, lat] of line) {
      const x = Math.round(lon / QUANTUM);
      const y = Math.round(lat / QUANTUM);
      const last = points[points.length - 1];
      if (!last || last[0] !== x || last[1] !== y) points.push([x, y]);
    }
    // Rings repeat their first point last; the reader closes them itself.
    if (closed && points.length > 1) {
      const [first, last] = [points[0]!, points[points.length - 1]!];
      if (first[0] === last[0] && first[1] === last[1]) points.pop();
    }
    if (points.length < (closed ? 3 : 2)) continue;
    values.push(points.length);
    for (const [x, y] of points) {
      values.push(zigzag(x - px), zigzag(y - py));
      px = x;
      py = y;
    }
    count++;
  }
  const out = encode(values);
  console.log(`${count} lines, ${out.length} characters`);
  return out;
}

const [landFile, bordersFile] = process.argv.slice(2);
if (!landFile || !bordersFile) {
  console.error("usage: build-earth-geography.ts <ne_50m_land.geojson> <ne_50m_admin_0_boundary_lines_land.geojson>");
  process.exit(1);
}

const wrap = (text: string) => text.match(/.{1,100}/g)!.map((row) => `  "${row}"`).join(" +\n");
fs.writeFileSync(
  OUTPUT_PATH,
  `// Generated by scripts/build-earth-geography.ts from Natural Earth 1:50m (public domain). Do not edit.\n\n` +
    `/** Land polygons: closed rings, holes included. */\n` +
    `export const LAND =\n${wrap(pack(read(landFile), true))};\n\n` +
    `/** Borders between countries on land. */\n` +
    `export const BORDERS =\n${wrap(pack(read(bordersFile), false))};\n`,
);
console.log(`Wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
