/**
 * Packs the stars of the Yale Bright Star Catalogue (5th revised edition,
 * Hoffleit & Warren 1991, via the Harvard–Smithsonian Center for
 * Astrophysics) down to magnitude 5.5 into `apps/earth/stars.generated.ts`
 * for the Earth app's sky.
 *
 *   curl -LO http://tdc-www.harvard.edu/catalogs/bsc5.dat.gz && gunzip bsc5.dat.gz
 *   npx tsx scripts/build-earth-stars.ts bsc5.dat
 *
 * Each star is three numbers (see `apps/earth/packing.ts`): right ascension
 * in hundredths of a degree as a zigzag delta from the star before, sorted
 * by it; declination in hundredths of a degree plus 9000; and visual
 * magnitude in tenths plus 20.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { encode, zigzag } from "../apps/earth/packing";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_PATH = path.join(ROOT, "apps", "earth", "stars.generated.ts");
const FAINTEST = 5.5;

const [file] = process.argv.slice(2);
if (!file) {
  console.error("usage: build-earth-stars.ts <bsc5.dat>");
  process.exit(1);
}

// Fixed columns, 1-based in the catalogue's ReadMe: RA (J2000) 76–83, Dec 84–90, V 103–107.
const field = (line: string, from: number, to: number) => line.slice(from - 1, to).trim();
const stars: { ra: number; dec: number; mag: number }[] = [];
for (const line of fs.readFileSync(file, "latin1").split("\n")) {
  const mag = Number.parseFloat(field(line, 103, 107));
  const rah = field(line, 76, 77);
  if (!rah || !Number.isFinite(mag) || mag > FAINTEST) continue;
  const ra = (Number(rah) + Number(field(line, 78, 79)) / 60 + Number(field(line, 80, 83)) / 3600) * 15;
  const sign = field(line, 84, 84) === "-" ? -1 : 1;
  const dec = sign * (Number(field(line, 85, 86)) + Number(field(line, 87, 88)) / 60 + Number(field(line, 89, 90)) / 3600);
  stars.push({ ra, dec, mag });
}
stars.sort((a, b) => a.ra - b.ra);

const values: number[] = [];
let previous = 0;
for (const { ra, dec, mag } of stars) {
  const x = Math.round(ra * 100);
  values.push(zigzag(x - previous), Math.round(dec * 100) + 9000, Math.round(mag * 10) + 20);
  previous = x;
}
const packed = encode(values);
const wrapped = packed.match(/.{1,100}/g)!.map((row) => `  "${row}"`).join(" +\n");
fs.writeFileSync(
  OUTPUT_PATH,
  `// Generated by scripts/build-earth-stars.ts from the Yale Bright Star Catalogue. Do not edit.\n\n` +
    `/** ${stars.length} stars to magnitude ${FAINTEST}, by right ascension. */\n` +
    `export const STARS =\n${wrapped};\n`,
);
console.log(`${stars.length} stars, ${packed.length} characters. Wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
