"""
Packs how bright the ground is, from NASA's Blue Marble (public domain:
"Whole world - land and oceans.jpg", NASA Goddard / Reto Stöckli, via
Wikimedia Commons), into apps/earth/imagery.generated.ts for the Earth app.

    curl -L -o bluemarble.jpg \
      "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Whole_world_-_land_and_oceans.jpg/3840px-Whole_world_-_land_and_oceans.jpg"
    python3 scripts/build-earth-imagery.py bluemarble.jpg

The picture is an equirectangular map, 180°N at the top and 180°W on the
left. It is shrunk to MAP_W x MAP_H, turned to luminance, stretched so the
land's range fills the levels, and cut to LEVELS levels. Each run of one
level along a row (rows follow on from each other) is one number,
`level + LEVELS * (length - 1)`, packed as `apps/earth/packing.ts` packs
numbers.
"""

import sys
from pathlib import Path

from PIL import Image

MAP_W = 1024
MAP_H = 512
LEVELS = 8
# Luminance (0-255) the levels stretch between: the sea is darker than the
# low end, and ice reaches the top.
LOW = 18
HIGH = 235
# Brighten the middle of the range a little, as the eye sees the imagery.
GAMMA = 0.85

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "apps" / "earth" / "imagery.generated.ts"


def encode(values):
    out = []
    for value in values:
        v = value
        while True:
            bits = v & 31
            v //= 32
            out.append(ALPHABET[bits | (32 if v > 0 else 0)])
            if v == 0:
                break
    return "".join(out)


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: build-earth-imagery.py <bluemarble.jpg>")
    image = Image.open(sys.argv[1]).convert("L").resize((MAP_W, MAP_H), Image.LANCZOS)
    pixels = list(image.getdata())

    def level(p):
        t = min(1.0, max(0.0, (p - LOW) / (HIGH - LOW))) ** GAMMA
        return min(LEVELS - 1, int(t * LEVELS))

    levels = [level(p) for p in pixels]
    values = []
    run_level = levels[0]
    run_length = 1
    for current in levels[1:]:
        if current == run_level:
            run_length += 1
        else:
            values.append(run_level + LEVELS * (run_length - 1))
            run_level = current
            run_length = 1
    values.append(run_level + LEVELS * (run_length - 1))

    packed = encode(values)
    rows = "".join(f'  "{packed[i:i + 100]}" +\n' for i in range(0, len(packed), 100)).rstrip(" +\n")
    OUTPUT.write_text(
        "// Generated by scripts/build-earth-imagery.py from NASA's Blue Marble (public domain). Do not edit.\n\n"
        f"export const IMAGERY_W = {MAP_W};\n"
        f"export const IMAGERY_H = {MAP_H};\n"
        f"export const IMAGERY_LEVELS = {LEVELS};\n\n"
        f"/** Runs of brightness levels along the rows, top to bottom: `level + {LEVELS} × (length − 1)`. */\n"
        f"export const IMAGERY =\n{rows};\n"
    )
    print(f"{len(values)} runs, {len(packed)} characters. Wrote {OUTPUT.relative_to(ROOT)}")


main()
